"""Add signup_data and is_signup_complete to User model

Revision ID: d6949d453c14
Revises: 7b958338dfde
Create Date: 2025-03-27 19:52:59.273228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6949d453c14'
down_revision = '7b958338dfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_signup_complete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_signup_complete')
        batch_op.drop_column('signup_data')

    # ### end Alembic commands ### 